version: '3.1'
services:
  frontend_user_server:
    build: ./Frontend
    ports:
      - "3000:3000"

  reservation_service_api:
    build: ./GNOGBackend
    # When deploy. It is recommended to not publish any backend(api) port.
    ports:
      - "5000:5000"

    # For accessing database on host machine port.
    extra_hosts:
      - "host.docker.internal:host-gateway"
