name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker compose down
        docker compose up --build -d 
        docker exec se_hotel_project-frontend_user_server-1 sh -c "touch ./.env"
        docker exec se_hotel_project-frontend_user_server-1 sh -c "echo \"${{ vars.FRONTEND_ENV }}\" >> ./.env"
        docker exec se_hotel_project-reservation_service_api-1 sh -c "touch ./.env"
        docker exec se_hotel_project-reservation_service_api-1 sh -c "echo \"${{ vars.BACKEND_ENV }}\" >> ./.env"
        docker stop se_hotel_project-frontend_user_server-1
        docker stop se_hotel_project-reservation_service_api-1
        docker start se_hotel_project-frontend_user_server-1
        docker start se_hotel_project-reservation_service_api-1
