name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: gh-rpi-runner-1

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose down
      run: docker compose up --build -d
